### ISSUE TITLE
nmea2tfpose sim mode not working.

### ISSUE THREAD

**Issue by cyberphysicalrobotics** [Autoware-AI/core_perception#10]
### Required information:

- Operating system and version:
  - Ubuntu 18.04
  
  
- Autoware installation type:
  - Locally generated docker container 
- Autoware version or commit hash
  - 43330aef349dde0d17d9a7050f5ae6bf808b73b3 
- ROS distribution and version:
  - melodic
- ROS installation type:
  - ROS was installed by docker script.
- Package or library, if applicable:
  - gnss_localizer

### Description of the bug

In gnss_localizer, nmea2tfpose has Simulation Mode. When I clicked it, /gnss_pose topic was not applied for simulation mode. With simulation mode activated, plane number 0 should be applied internally. However, regardless of simulation mode activation, existed plane number is still be applying to the gnss_localizer node.

### Steps to reproduce the bug

1. Launch lgsvl simulator.
2. Launch runtime_manager
```
$ roslaunch runtime_manager runtime_manager.launch
```
3. On the Quick Start tab, activate Map, Sensing, Localization.
4. On Computing tab, click app for nmea2tfpose in gnss_localizer.
5. Click Simulation Mode.
6. Check rostopic echo like the following
```
$ rostopic echo /gnss_pose -n 1
```

### Expected behavior

/gnss_pose has pose without adding origin coordinate 
When plane number is 7, simulation mode is activated
```
$ rostopic echo /gnss_pose -n 1
header: 
  seq: 78
  stamp: 
    secs: 1595346468
    nsecs: 615610624
  frame_id: "map"
pose: 
  position: 
    x: -9.03081818061
    y: 50.3633886972
    z: -1.122381
  orientation: 
    x: 0.550936004788
    y: 0.569652790116
    z: 0.42817032443
    w: 0.434321759319
---
```
### Actual behavior

When plane number is 7, simulation mode is activated
```
$ rostopic echo /gnss_pose -n 1
header: 
  seq: 0
  stamp: 
    secs: 1595346281
    nsecs: 445789184
  frame_id: "map"
pose: 
  position: 
    x: -86029096.0418
    y: -3981885.24795
    z: -1.122381
  orientation: 
    x: 0.550936004788
    y: 0.569652790116
    z: 0.42817032443
    w: 0.434321759319
---
```

**Comment by JWhitleyWork** [comment]
Closed by #11.
