### ISSUE TITLE
The link for the weights file in trafficlight_recognizer/region_tlr_ssd is unavailable

### ISSUE THREAD

**Issue by JWhitleyWork** [Autoware-AI/core_perception#16]
Originally reported as Autoware-AI/autoware.ai#2348

### Required information:

- Operating system and version: 
  - Ubuntu 18.04
- Autoware installation type:
  - source
- Autoware version or commit hash
  - 1.14.0
- ROS distribution and version:
  - melodic
- ROS installation type:
  - binary
- Package or library, if applicable:
  - trafficlight_recognizer/region_tlr_ssd
### Description of the bug

The link for the ssd model is broken.
doc: https://github.com/Autoware-AI/core_perception/tree/master/trafficlight_recognizer/nodes/region_tlr_ssd
link: http://db3.ertl.jp/autoware/tlr_trained_model/data.tar.bz2

**Comment by TakaHoribe** [comment]
@JWhitleyWork I put the original data here. Could you update the link?

https://drive.google.com/file/d/1rgjLzDgw4LhuPqFKnHWMBZBTeu8NoGHy/view?usp=sharing
(This data will be removed when this PR is closed)

The data server seems to be moved to the AWS.
https://github.com/Autoware-AI/autoware.ai/wiki/ROSBAG-Demo#demo-data

**Comment by JWhitleyWork** [comment]
@TakaHoribe Thank you for looking into this. I'm glad you found it! Feel free to remove your copy in Drive. Here is a link to the file on our AWS S3 instance: https://autoware-ai.s3.us-east-2.amazonaws.com/region_tlr_ssd_trained_weights.tar.bz2

Would you or @francis0407 mind creating a Pull Request to update the link in the README for the package?

**Comment by francis0407** [comment]
@JWhitleyWork  I'll open a PR for that, thanks!

**Comment by JWhitleyWork** [comment]
Closed by autowarefoundation/autoware#17.
