### ISSUE TITLE
Using Local Cone Height threshold only, While Checking a Point is a Ground Point

### ISSUE THREAD

**Issue by yucedagonurcan** [Autoware-AI/core_perception#24]
Hello,

# Required information:

## Operating system and version
- Ubuntu 18.
## Autoware installation type:
- Source 
## Autoware version or commit:
-  0.13.0 version

## ROS distribution and version
- melodic
## ROS installation :
- Source build

## Package or library, if applicable
- ray_ground_filter

If current point is not in the local cone of the previous point:

- If they are closer than reclass_distance_threshold_, current point is not ground.
- If they are far from each other and current point's height is in the general_height_threshold (Global Cone), current_point is a ground point.

But above logic is not what implemented in the code. You can see we are using only height_threshold rather than using general_height_threshold while we are checking for Global Cone.

https://github.com/Autoware-AI/core_perception/blob/402ea985234c0fe30c3f3f944cb8663039295912/points_preprocessor/nodes/ray_ground_filter/ray_ground_filter.cpp#L195-L197

Shouldn't it be:
```
 // check if previous point is too far from previous one, if so classify again
if (points_distance > reclass_distance_threshold_ &&
            (current_height <= general_height_threshold && current_height >= -general_height_threshold))
```

Am I missing something?

Have a great day.

**Comment by pedroexenberger** [comment]
I second this understanding. Asked the same some time ago [at ros answers](https://answers.ros.org/question/359694/ray_ground_filter-differing-from-specification), but got no confirmation there.

**Comment by JWhitleyWork** [comment]
I have asked @TakaHoribe to take a look. I'm sorry that it hasn't been answered sooner.

**Comment by TakaHoribe** [comment]
I checked the code, and it should be fixed. We'll take this issue and create the fix PR soon. Thank you very much for your report!
