### ISSUE TITLE
lidar_euclidean_cluster_detect output topics are not transformed properly.

### ISSUE THREAD

**Issue by MaxandreOgeret** [Autoware-AI/core_perception#36]
/label ~bug

### Required information:
- Operating system and version: Ubuntu 18.04
- Autoware installation type: Source
- Autoware version or commit hash OAP7
- ROS distribution and version: Ros melodic
- ROS installation type: APT
- Package or library, if applicable: lidar_euclidean_cluster_detect

### Description of the bug

lidar_euclidean_cluster_detect output topics are not fully transformed.

#### CloudCluster in `/detection/lidar_detector/cloud_clusters`

Transformed properly :
 - `min_point`
 - `max_point`
 - `avg_point`
 - `centroid_point`

Not transformed : 
 - `convex_hull`
 - `bounding_box`

Because this message is not TFed properly the messages published in `/detection/lidar_detector/objects` are also wrong :

#### DetectedObject in `/detection/lidar_detector/objects`

Transformed properly :
 - None

Not transformed : 
 - `pose`
 - `convex_hull`

### Steps to reproduce the bug

 - Configure lidar_euclidean_cluster_detect output frame different from the input frame.
 - Publish pointclouds to the `/points_raw` topic.
 - Open rqt and notice that some data is not tfed.

### Screenshots

![image](https://user-images.githubusercontent.com/22786578/97026502-22d08000-1562-11eb-86ce-39a102ac23a3.png)
The points are still in Lidar frame and not map frame, even if the header says so ! It really looks like a bug.

### Additional information

I have corrected the bug.
One question though, what is the best way to TF a [Point32](http://docs.ros.org/en/melodic/api/geometry_msgs/html/msg/Point32.html) ? Because the TF listener has no `transformPoint32` function.

Thanks !

**Comment by JWhitleyWork** [comment]
@MaxandreOgeret `geometry_msgs/Point` is recommended over `geometry_msgs/Point32` due to the increased precision. To that end, `tf2_geometry_msgs` supports conversion of `geometry_msgs/Point` and `geometry_msgs/PointStamped` to/from `tf2` types and can then have transforms applied easily.
