### ISSUE TITLE
naive_motion_predict subscribed topic

### ISSUE THREAD

**Issue by ahmedius2** [Autoware-AI/core_perception#4]
### Required information:

- Operating system and version:
Ubuntu 18.04
- Autoware installation type: Source
- Autoware version or commit hash: 1.14.0
- ROS distribution and version: Melodic
- ROS installation type: Package manager
- Package or library, if applicable: naive_motion_predict

### Description of the bug
The subscribed topic is outdated in documentation page of naive_motion_predict. It should be updated to /detection/objects from /detection/lidar_tracker/objects.

**Comment by JWhitleyWork** [comment]
@ahmedius2 Would you mind creating a Pull Request to update the documentation page?

**Comment by ahmedius2** [comment]
Sure!

**Comment by JWhitleyWork** [comment]
Closed by #5.
