### ISSUE TITLE
Support for Noetic

### ISSUE THREAD

**Issue by Timple** [Autoware-AI/core_perception#40]
## Feature request

Support for ROS Noetic 

### Description

We're using the `points_processor` package and are transitioning to ROS Noetic. 

### Implementation considerations

A separate branch for Noetic changes would already help. I've made some changes for the new velodyne release (Noetic uses 1.6.1). It would be nice if I could target these changes against a noetic branch so other people don't have to go to the same trouble.

### Alternatives

Everybody repeats this effort :eyeglasses:

**Comment by JWhitleyWork** [comment]
@Timple While I totally approve of this effort, Autoware.AI is going into maintenance-only mode after the 1.15.0 release, expected around the end of this year (see relevant Discourse post here: https://discourse.ros.org/t/end-of-life-dates-for-autoware-ai/13750). Unfortunately, The Autoware Foundation simply doesn't have time to maintain *and develop* both Autoware.AI and Autoware.Auto. The Foundation would likely be open to having an organization, group of organizations, or group of individuals take over maintenance of Autoware.AI if there is enough interest (would need approval from the Technical Steering Committee) but the Foundation is very resource-constrained and simply can't dedicate the resources to it at this time.
