### ISSUE TITLE
error: could not convert ‘cv::Scalar_<double>((double)0, (double)255, (double)255, (double)0)’ from ‘cv::Scalar {aka cv::Scalar_<double>}

### ISSUE THREAD

**Issue by shandaolu** [Autoware-AI/core_perception#44]
Hello,I met the problem.How can I solve it?

In file included from /usr/local/include/opencv2/imgproc/imgproc.hpp:48:0,
                 from /opt/ros/melodic/include/cv_bridge/cv_bridge.h:44,
                 from /home/alpha/autoware.ai-1.14.0/src/autoware/core_perception/vision_lane_detect/nodes/vision_lane_detect/vision_lane_detect.cpp:37:
/home/alpha/autoware.ai-1.14.0/src/autoware/core_perception/vision_lane_detect/nodes/vision_lane_detect

/vision_lane_detect.cpp: In function ‘void process_image_common(IplImage*)’:
/home/alpha/autoware.ai-1.14.0/src/autoware/core_perception/vision_lane_detect/nodes/vision_lane_detect/vision_lane_detect.cpp:514:58: error: could not convert ‘cv::Scalar_<double>((double)0, (double)255, (double)255, (double)0)’ from ‘cv::Scalar {aka cv::Scalar_<double>}’ to ‘CvScalar’
          cvPoint(frame_size.width/2, frame_size.height), CV_RGB(255, 255, 0), 1);
                                                          ^
/home/alpha/autoware.ai-1.14.0/src/autoware/core_perception/vision_lane_detect/nodes/vision_lane_detect/vision_lane_detect.cpp: In function ‘void lane_cannyhough_callback(const Image&)’:
/home/alpha/autoware.ai-1.14.0/src/autoware/core_perception/vision_lane_detect/nodes/vision_lane_detect/vision_lane_detect.cpp:544:30: error: conversion from ‘cv::Mat’ to non-scalar type ‘IplImage {aka _IplImage}’ requested
   IplImage frame = cv_image->image;
                    ~~~~~~~~~~^~~~~
make[2]: *** [CMakeFiles/vision_lane_detect.dir/nodes/vision_lane_detect/vision_lane_detect.cpp.o] Error 1
make[1]: *** [CMakeFiles/vision_lane_detect.dir/all] Error 2
make: *** [all] Error 2

**Comment by JWhitleyWork** [comment]
Please see our [Support Guidelines](https://github.com/Autoware-AI/autoware.ai/wiki/Support-guidelines) on how to get support. This starts with asking a question on [ROS Answers](https://answers.ros.org/) with the `autoware` tag.
