### ISSUE TITLE
pcl_omp_registration not building on Ubuntu 20.04 / Noetic

### ISSUE THREAD

**Issue by flynneva** [Autoware-AI/core_perception#48]
### Required information:

- Operating system and version: 
  - Ubuntu 20.04
- Autoware installation type:
  - from source
- Autoware version or commit hash
  - 411330c5bb0eb5a963393f869c19d7815bb2dafc
- ROS distribution and version:
  - ROS Noetic
- ROS installation type:
  - binary installation (add ppa, sudo apt install)
- Package or library, if applicable:
  - `pcl_omp_registration`

### Description of the bug
After cloning and installing dependencies using `rosdep` I would expect everything to compile fine. Running `catkin_make` runs into an error on the `pcl_omp_registration` package and stalls out.

### Steps to reproduce the bug

1. git clone this repo & repos stated in `build_depends.repo` file
2. rosdep install --from-paths src --ignore-src -r -y
3. missing one dependency still so clone `tmv_vendor` to fix it
4. run `catkin_make`

### Expected behavior
builds clean

### Actual behavior
errors out on `pcl_omp_registration`

### Additional information
Copy & pasted some of the errors for reference:
```
code/ros/noetic/src/core_perception/pcl_omp_registration/include/pcl_omp_registration/registration.h:181:23: error: expected identifier before string constant
  181 |       PCL_DEPRECATED ("[pcl::registration::Registration::setInputCloud] setInputCloud is deprecated. Please use setInputSource instead.")
      |                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

```
error: ‘int pcl_omp::Registration<PointSource, PointTarget, Scalar>::PCL_DEPRECATED(int)’ cannot be overloaded with ‘int pcl_omp::Registration<PointSource, PointTarget, Scalar>::PCL_DEPRECATED(int)’
  186 |       PCL_DEPRECATED ("[pcl::registration::Registration::getInputCloud] getInputCloud is deprecated. Please use getInputSource instead.")
```

```
code/ros/noetic/src/core_perception/pcl_omp_registration/include/pcl_omp_registration/registration.h:181:7: note: previous declaration ‘int pcl_omp::Registration<PointSource, PointTarget, Scalar>::PCL_DEPRECATED(int)’
  181 |       PCL_DEPRECATED ("[pcl::registration::Registration::setInputCloud] setInputCloud is deprecated. Please use setInputSource instead.")
```

```
code/ros/noetic/src/core_perception/pcl_omp_registration/include/pcl_omp_registration/registration.h:375:45: error: ‘boost::function’ has not been declared
  375 |       registerVisualizationCallback (boost::function<FunctionSignature> &visualizerCallback)
      |                                             ^~~~~~~~
```

```
code/ros/noetic/src/core_perception/pcl_omp_registration/include/pcl_omp_registration/registration.h:575:14: error: ‘function’ in namespace ‘boost’ does not name a template type; did you mean ‘is_function’?
  575 |       boost::function<void(const pcl::PointCloud<PointSource> &cloud_src,
      |              ^~~~~~~~
      |              is_function
```

```
code/ros/noetic/src/core_perception/pcl_omp_registration/include/pcl_omp_registration/registration.h:377:13: error: ‘visualizerCallback’ was not declared in this scope
  377 |         if (visualizerCallback != NULL)
```

**Comment by JWhitleyWork** [comment]
Per our [support guidelines](https://github.com/Autoware-AI/autoware.ai/wiki/Support-guidelines), support questions and unconfirmed bugs should be asked at ROS Answers. Additionally, Autoware.AI only supports ROS Melodic.

**Comment by SharkPeppero** [comment]
I made the same mistake, how did you solve it at last

**Comment by haixuanTao** [comment]
For people interested, I have fixed the header file as follows: https://github.com/Kin-Zhang/simple_ndt_slam/pull/2/files
