### ISSUE TITLE
Is the angular velocity of imu  Euler angle representation in ndt_mapping.cpp?

### ISSUE THREAD

**Issue by nonlinear1** [Autoware-AI/core_perception#49]
In the line 298 of core_perception/lidar_localizer/nodes/ndt_mapping/ndt_mapping.cpp, 
 the function static void imu_calc(ros::Time current_time) calculate 
 the diff_imu_roll、diff_imu_pitch、diff_imu_yaw with the following statements:
  double diff_imu_roll = imu.angular_velocity.x * diff_time;
  double diff_imu_pitch = imu.angular_velocity.y * diff_time;
  double diff_imu_yaw = imu.angular_velocity.z * diff_time;
 I am confused with the mu.angular_velocity. is the mu.angular_velocity Euler angle representation? I think generally speaking
this is not. Could someone tell me why in here the  angular_velocity of imu is Euler angle representation?

**Comment by JWhitleyWork** [comment]
@nonlinear1 Please submit support questions to [ROS Answers](https://answers.ros.org/) with the tag `autoware`.
