### ISSUE TITLE
Ndt_mapping not working

### ISSUE THREAD

**Issue by mertyavuzAdastec** [Autoware-AI/core_perception#53]
**Required information:**
    • Operating system and version: 
        ◦ Ubuntu 18.04
    • Autoware installation type: 
        ◦ From source 
    • Autoware version or commit hash 
        ◦ Master version
    • ROS distribution and version: 
        ◦ Melodic
    • ROS installation type: 
        ◦ Binary
    • Package or library, if applicable: 
        ◦ Ndt_mapping

**Description of the bug**
Ndt_mapping did not work. When I start the bag file which includes /points_raw and /vehicle_twist topics, the transformation matrix seems to be empty(zero matrix). When the ndt_mapping process terminated via requesting a pcd output with runtime manager, generated pcd can not be loaded with points_map_loader. Points_map_loader returns “no loaded points” as a warning.

**Steps to reproduce the bug**
Start ndt_mapping using by Runtime Manager GUI, after starting the bag file.

**Expected behavior**
Ndt_mapping should create pcd file.

**Actual behavior**
Created pcd file is broken or empty.

**Screenshots**
Autoware-1.15 behavior:
![Screenshot from 2021-04-08 17-43-34](https://user-images.githubusercontent.com/73120336/114056679-96f5aa80-989a-11eb-9ef0-770573d4cd72.png)

Autoware-1.12 behavior:
![Screenshot from 2021-04-08 17-51-07](https://user-images.githubusercontent.com/73120336/114056753-a70d8a00-989a-11eb-9733-3e37fbe6a75c.png)

**Additional information**
I’ve tried ndt_mapping different version of autoware.ai(1.12 and 1.14) with same bag file and it has worked.

**Comment by JWhitleyWork** [comment]
@mertyavuzAdastec Please submit support requests and unconfirmed bugs to [ROS Answers](https://answers.ros.org/) with the `autoware` tag.
