### ISSUE TITLE
vision_darknet_detect fails to "tag" traffic lights, stop signs, and speed signs

### ISSUE THREAD

**Issue by squizz617** [Autoware-AI/core_perception#57]
### Required information:

- Operating system and version: Ubuntu 18.04
- Autoware installation type: Docker image `autoware/autoware:1.14.0-melodic-cuda`, as specified in the Dockerfile of `https://github.com/carla-simulator/carla-autoware` at commit `975b6f3`.
- Autoware version or commit hash - 1.14.0
- ROS distribution and version:
  - ROS Melodic (pre-installed in the docker image)
- ROS installation type:
  - Pre-installed in the docker image

### Description of the bug

* I am running Autoware 1.14.0 (docker image: `autoware/autoware:1.14.0-melodic-cuda`), Carla 0.9.10.1 (docker image: `carlasim/carla:0.9.10.1`) as a simulator and [carla-autoware-bridge](https://github.com/carla-simulator/carla-autoware) at `975b6f3` as a bridge.
* Using `vision_darknet_detect` with files `yolov3.cfg`, `yolov3.weight`, and `coco.names` provided in the repository, object detection works well with cars and walkers; they get detected and tagged properly as cars and walkers. However, the speed signs, stop signs, and traffic lights are being recognized, but not semantically tagged; they are tagged as "unknown #"
  * This can be observed in the captured [rviz](https://drive.google.com/file/d/1rvZof1lijHaJNeWAt1SRvkM5hF8lum4U/view?usp=sharing).
* Please refer to the [rosbag file](https://drive.google.com/file/d/1z-OA1ePjY9WZKIVPtyvjZdITmha2X5Np/view?usp=sharing) for detailed trace.

### Steps to reproduce the bug

1. Replay the self-contained [rosbag file](https://drive.google.com/file/d/1z-OA1ePjY9WZKIVPtyvjZdITmha2X5Np/view?usp=sharing).

### Expected behavior
Traffic lights, stop signs, and speed signs are recognized, and tagged as what they are.

### Actual behavior
They are recognized, but get "unknown" tags.

### Screenshots
![speed_signs](https://user-images.githubusercontent.com/10861633/116827942-ca5de900-ab69-11eb-9626-fee927ea41dc.png)
![traffic_light](https://user-images.githubusercontent.com/10861633/116827950-d0ec6080-ab69-11eb-9d22-fbe2197c8c1e.png)

### Additional information

P.S. Thank you for prompt replies!

**Comment by JWhitleyWork** [comment]
@squizz617 Per our [Support Guidelines](https://github.com/Autoware-AI/autoware.ai/wiki/Support-guidelines), support requests and unconfirmed bugs should first be posted to [ROS Answers](https://answers.ros.org) with the `autoware` tag.

**Comment by liyunwei-3558** [comment]
Hello, I encountered the same question and it puzzled me a lot. Have you solved this issue? Looking forward to your reply.
