### ISSUE TITLE
Where is the .clang-format for this repository?

### ISSUE THREAD

**Issue by xmba15** [Autoware-AI/core_perception#8]
Hi. I have used a bit of code here and would like to contribute back (a little bit of refactoring for the shape fitter if the repository owner does not mind). Then, I notice I can not find an open clang-formatter anywhere though the log said clang-formatter has been applied.
https://github.com/Autoware-AI/core_perception/blob/f14a0ca32d57ab87477cd5fb3e96656320bc497e/lidar_fake_perception/CHANGELOG.rst#180-2018-08-31

If able, can you add an open format for clang-formatter, which makes it easier for contributors?

Sorry if it is wrong to label this issue as "bug" :)

**Comment by JWhitleyWork** [comment]
@xmba15 The `.clang-format` file that was used can be found here: https://github.com/davetcoleman/roscpp_code_format/blob/master/.clang-format. In addition, `roslint` has been applied to several of the packages, which enforces many of the same formatting rules. Would you mind creating a PR to add the `.clang-format` file? We would also be happy to accept PRs which apply it to other packages (many packages do not have it applied) and enforce it through `roslint`.

**Comment by JWhitleyWork** [comment]
Closed by #9.
